export type Lang = "ur" | "en";

export const COPY = {
  ur: {
    brand: "SL Fit",
    tagline: "SL ke beech apna dollar risk fit karo — exact leverage nikal ke aata hai.",
    long: "Long",
    short: "Short",
    entry: "Entry price",
    stop: "Stop loss",
    risk: "Risk (USDT)",
    riskHint: "SL hit pe itna nuksaan lena hai",
    wallet: "Available margin",
    walletHint: "Khali chhoro agar sirf risk jitna isolated lagana hai",
    buffer: "Liq buffer",
    bufferOff: "Off",
    bufferOn: "10%",
    fees: "Taker fees 0.04% × 2",
    levLabel: "Leverage",
    noLev: "Extra leverage ki zaroorat nahi",
    minLev: "Minimum leverage",
    position: "Position size",
    qty: "Quantity",
    margin: "Margin lock",
    slMove: "SL distance",
    liq: "Est. liquidation",
    copy: "Copy setup",
    copied: "Copied",
    example: "Example load karo",
    langEn: "EN",
    langUr: "UR",
    invalid: "Entry, SL aur risk positive numbers hone chahiye.",
    same: "SL aur entry same nahi ho sakte.",
    longSl: "Long ke liye SL entry se neeche hona chahiye.",
    shortSl: "Short ke liye SL entry se upar hona chahiye.",
    hintLong: "Buy / up",
    hintShort: "Sell / down",
    stepQty: "Pehle quantity — yahi $ risk ko SL pe fit karti hai.",
    stepLev: "Leverage sirf itna margin lock karne ke liye hai. Risk leverage se nahi, size se fix hota hai.",
    openAt1x:
      "Wallet / margin is position ko 1x pe cover kar leta hai. Extra leverage mat lagaao — SL pe phir bhi sirf aapka diya hua risk lagega.",
    needLev:
      "Itne margin se ye position kholne ke liye kam se kam itni leverage chahiye. Is se zyada lagaoge to liquidation SL ke qareeb aa jayegi.",
    liqWarn:
      "Is leverage pe liquidation SL se pehle aa sakti hai. Thoda extra margin rakho ya buffer on karo.",
    slFirst: "SL liquidation se pehle hit hoga.",
    footnote:
      "Risk quantity se fix hota hai. Leverage sirf ye decide karti hai ke kitna margin lock hoga.",
    recipeTitle: "Order recipe",
    setLev: "Set leverage",
    placeQty: "Place qty",
    isolate: "Isolated margin",
    classic: "Agar sirf risk isolate karo",
  },
  en: {
    brand: "SL Fit",
    tagline: "Fit your dollar risk into the stop. Get the exact leverage to open it.",
    long: "Long",
    short: "Short",
    entry: "Entry price",
    stop: "Stop loss",
    risk: "Risk (USDT)",
    riskHint: "Max loss if the stop hits",
    wallet: "Available margin",
    walletHint: "Leave empty to isolate exactly your risk (plus buffer)",
    buffer: "Liq buffer",
    bufferOff: "Off",
    bufferOn: "10%",
    fees: "Taker fees 0.04% × 2",
    levLabel: "Leverage",
    noLev: "No extra leverage needed",
    minLev: "Minimum leverage",
    position: "Position size",
    qty: "Quantity",
    margin: "Margin locked",
    slMove: "SL distance",
    liq: "Est. liquidation",
    copy: "Copy setup",
    copied: "Copied",
    example: "Load example",
    langEn: "EN",
    langUr: "UR",
    invalid: "Entry, stop and risk must be positive numbers.",
    same: "Stop and entry cannot be the same.",
    longSl: "For a long, the stop must be below entry.",
    shortSl: "For a short, the stop must be above entry.",
    hintLong: "Buy / up",
    hintShort: "Sell / down",
    stepQty: "Size the quantity first — that is what fits $ risk into the stop.",
    stepLev: "Leverage only decides how much margin you lock. Risk is size, not leverage.",
    openAt1x:
      "Your margin covers this position at 1x. Do not add leverage — the stop still costs only the risk you set.",
    needLev:
      "This is the minimum leverage to open that size with the margin you have. Higher leverage pulls liquidation closer to the stop.",
    liqWarn:
      "At this leverage, liquidation may hit before the stop. Add margin or turn the buffer on.",
    slFirst: "Stop should hit before liquidation.",
    footnote:
      "Risk is fixed by quantity. Leverage only decides how much margin is locked.",
    recipeTitle: "Order recipe",
    setLev: "Set leverage",
    placeQty: "Place qty",
    isolate: "Isolated margin",
    classic: "If you isolate only the risk",
  },
} as const;

export type Copy = (typeof COPY)[Lang];
